# Generated by Django 3.2 on 2021-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takimismi', models.CharField(max_length=50, verbose_name='Takım')),
                ('sira', models.CharField(max_length=2, verbose_name='Kaçıncı Sıra')),
                ('bayrak', models.FileField(upload_to='', verbose_name='Takımın Bayrağı')),
                ('o', models.CharField(max_length=2, verbose_name='O')),
                ('g', models.CharField(max_length=2, verbose_name='G')),
                ('b', models.CharField(max_length=2, verbose_name='B')),
                ('m', models.CharField(max_length=2, verbose_name='M')),
                ('a', models.CharField(max_length=2, verbose_name='A')),
                ('y', models.CharField(max_length=2, verbose_name='Y')),
                ('av', models.CharField(max_length=2, verbose_name='AV')),
                ('p', models.IntegerField(verbose_name='P')),
            ],
            options={
                'ordering': ['-p'],
            },
        ),
    ]
