# Generated by Django 3.2 on 2021-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Takım', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='sira',
        ),
        migrations.AlterField(
            model_name='club',
            name='a',
            field=models.IntegerField(verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='club',
            name='av',
            field=models.IntegerField(verbose_name='AV'),
        ),
        migrations.AlterField(
            model_name='club',
            name='b',
            field=models.IntegerField(verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='club',
            name='g',
            field=models.IntegerField(verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='club',
            name='m',
            field=models.IntegerField(verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='club',
            name='o',
            field=models.IntegerField(verbose_name='O'),
        ),
        migrations.AlterField(
            model_name='club',
            name='y',
            field=models.IntegerField(verbose_name='Y'),
        ),
    ]
