# Generated by Django 3.2 on 2021-05-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Takım', '0002_auto_20210521_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=250, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('futbolcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Takım.club', verbose_name='Kulüp')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
