# Generated by Django 3.2 on 2021-05-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Takım', '0003_commentclub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentclub',
            old_name='futbolcu',
            new_name='club',
        ),
    ]
