# Generated by Django 3.2 on 2021-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_tarihi', models.DateTimeField(auto_created=True, verbose_name='Bonservis Bitiş Tarihi')),
                ('isim_soyisim', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('dogumYili', models.CharField(max_length=4, verbose_name='Futbolcunun Doğum Yılı')),
                ('ulke', models.CharField(max_length=50, verbose_name='Futbolcunun Uyruğu')),
                ('nowTakim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Futbolcunun Oynadığı Takım')),
                ('enSonFiyat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Son Satış Bedeli')),
                ('mevki', models.CharField(max_length=50, verbose_name='Oynadığı Mevki')),
                ('ayak', models.CharField(max_length=50, verbose_name='Etkili Ayak')),
                ('fiziksel', models.TextField(max_length=50, verbose_name='Fiziksel Özellikleri')),
            ],
        ),
    ]
