# Generated by Django 3.2 on 2021-04-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='fiziksel',
        ),
    ]
