# Generated by Django 3.2 on 2021-04-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0002_remove_footballer_fiziksel'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf ekleme'),
        ),
    ]
