# Generated by Django 3.2 on 2021-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0005_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='enSonFiyat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Son Satış Bedeli'),
        ),
    ]
