# Generated by Django 3.2 on 2021-04-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0006_alter_footballer_ensonfiyat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
