# Generated by Django 3.2 on 2021-05-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0008_yorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilk', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
                ('ikinci', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
                ('ucuncu', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
            ],
        ),
    ]
