# Generated by Django 3.2 on 2021-05-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0009_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='İsim')),
                ('comment_content', models.TextField(max_length=250, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('futbolcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Footballer.footballer', verbose_name='Futbolcu')),
            ],
        ),
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
