# Generated by Django 3.2 on 2021-05-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0014_auto_20210502_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
