# Generated by Django 3.2 on 2021-05-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0015_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
