# Generated by Django 3.2 on 2021-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0016_delete_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinci_resim', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
                ('birinci_isim', models.CharField(max_length=50, verbose_name='İsim')),
                ('ikinci_resim', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
                ('ikinci_isim', models.CharField(max_length=50, verbose_name='İsim')),
                ('ucuncu_resim', models.FileField(upload_to='', verbose_name='Birinci Yıldız')),
                ('ucuncu_isim', models.CharField(max_length=50, verbose_name='İsim')),
            ],
        ),
    ]
