# Generated by Django 3.2 on 2021-05-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0018_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
