# Generated by Django 3.2 on 2021-05-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Footballer', '0019_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif', models.CharField(max_length=20, verbose_name='Teklif Bedeli')),
                ('futbolcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Footballer.footballer', verbose_name='Futbolcu')),
                ('teklif_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
