# Generated by Django 3.2 on 2021-12-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Takım', '0004_rename_futbolcu_commentclub_club'),
        ('Footballer', '0020_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='nowTakim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Takım.club'),
        ),
    ]
