# Generated by Django 3.2 on 2021-12-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0021_alter_footballer_nowtakim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballer',
            old_name='nowTakim',
            new_name='takim',
        ),
    ]
