# Generated by Django 3.2 on 2021-12-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Takım', '0004_rename_futbolcu_commentclub_club'),
        ('Footballer', '0024_alter_footballer_takim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takım.club'),
        ),
    ]
