# Generated by Django 3.2 on 2021-12-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0025_alter_footballer_takim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballer',
            old_name='takim',
            new_name='nowTakim',
        ),
    ]
